INSERT INTO WAREHOUSES (ADDRESS) VALUES ('CALLE 27')
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE) VALUES ('Bananas de colombia','BANANOS',1)
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE) VALUES ('Manzanas de Uruguay','MANZANAS',1)
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE) VALUES ('Mangos de Argentina','MANGOS',1)
