

INSERT INTO WAREHOUSES (ADDRESS) VALUES ('CALLE 27')
insert into Warehouses (id_Warehouse, address, location, province) values (2, '07 Daystar Court', 'Milwaukee', 'Porto');

insert into SECTIONS (section_id, BATCH_QUANTITY, MAX_SIZE, MIN_SIZE, WAREHOUSE_CODE) values (1, 36, 72, 31, 10);

INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE, PRICE) VALUES ('Bananas de colombia','BANANOS',1, 12.0)
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE, PRICE) VALUES ('Manzanas de Uruguay','MANZANAS',1, 10.0)
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE, PRICE) VALUES ('Mangos de Argentina','MANGOS',1, 8.5)

insert into BATCHES (BATCH_NUMBER, INITIAL_QUANTITY, CURRENT_QUANTITY, MANUFACTURING_TIME, MANUFACTURING_DATE, CURRENT_TEMPERATURE, MINIMUM_TEMPERATURE, FK_PRODUCT, DUE_DATE) values (1, 734, 229, '2021-08-04 02:19:34', '2021-04-04', 3, 3, 1, '2021-08-30');
insert into BATCHES (BATCH_NUMBER, INITIAL_QUANTITY, CURRENT_QUANTITY, MANUFACTURING_TIME, MANUFACTURING_DATE, CURRENT_TEMPERATURE, MINIMUM_TEMPERATURE, FK_PRODUCT, DUE_DATE) values (2, 69, 352, '2021-08-29 01:53:42', '2021-03-29', -9, 9, 2, '2021-08-03');


