INSERT INTO WAREHOUSES (ADDRESS) VALUES ('CALLE 27')
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE) VALUES ('Bananas de colombia','BANANOS',2)
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE) VALUES ('Manzanas de Uruguay','MANZANAS',2)
INSERT INTO PRODUCTS (ADDITIONAL_INFO,NAME,STATE) VALUES ('Mangos de Argentina','MANGOS',2)

